cpl=g++
clt=client/client_main.cpp
svr=server/server_main.cpp

client: $(clt) package.cpp
	$(cpl) -o $(clt) package.cpp

server: $(svr) package.cpp
	$(cpl) -o $(svr) package.cpp

client.o: $(clt) package.h
	%(cpl) -c $(clt) package.h

server.o: server/server.cpp package.h
	%(cpl) -c $(svr) package.h
	 
package.o: package.cpp  package.h
	%(cpl) -c package.cpp package.h
